package com.lawyer.domain;

import static com.lawyer.domain.AssertUtils.zonedDataTimeSameInstant;
import static org.assertj.core.api.Assertions.assertThat;

public class CaseSessionAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseSessionAllPropertiesEquals(CaseSession expected, CaseSession actual) {
        assertCaseSessionAutoGeneratedPropertiesEquals(expected, actual);
        assertCaseSessionAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseSessionAllUpdatablePropertiesEquals(CaseSession expected, CaseSession actual) {
        assertCaseSessionUpdatableFieldsEquals(expected, actual);
        assertCaseSessionUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseSessionAutoGeneratedPropertiesEquals(CaseSession expected, CaseSession actual) {
        assertThat(actual)
            .as("Verify CaseSession auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseSessionUpdatableFieldsEquals(CaseSession expected, CaseSession actual) {
        assertThat(actual)
            .as("Verify CaseSession relevant properties")
            .satisfies(a -> assertThat(a.getSessionDate()).as("check sessionDate").isEqualTo(expected.getSessionDate()))
            .satisfies(a ->
                assertThat(a.getSessionTime())
                    .as("check sessionTime")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getSessionTime())
            )
            .satisfies(a -> assertThat(a.getDescription()).as("check description").isEqualTo(expected.getDescription()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a ->
                assertThat(a.getCreatedAt())
                    .as("check createdAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getCreatedAt())
            )
            .satisfies(a ->
                assertThat(a.getUpdatedAt())
                    .as("check updatedAt")
                    .usingComparator(zonedDataTimeSameInstant)
                    .isEqualTo(expected.getUpdatedAt())
            );
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseSessionUpdatableRelationshipsEquals(CaseSession expected, CaseSession actual) {
        assertThat(actual)
            .as("Verify CaseSession relationships")
            .satisfies(a -> assertThat(a.getClient()).as("check client").isEqualTo(expected.getClient()))
            .satisfies(a -> assertThat(a.getCourtCase()).as("check courtCase").isEqualTo(expected.getCourtCase()));
    }
}
