package com.lawyer.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CaseStatusAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseStatusAllPropertiesEquals(CaseStatus expected, CaseStatus actual) {
        assertCaseStatusAutoGeneratedPropertiesEquals(expected, actual);
        assertCaseStatusAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseStatusAllUpdatablePropertiesEquals(CaseStatus expected, CaseStatus actual) {
        assertCaseStatusUpdatableFieldsEquals(expected, actual);
        assertCaseStatusUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseStatusAutoGeneratedPropertiesEquals(CaseStatus expected, CaseStatus actual) {
        assertThat(actual)
            .as("Verify CaseStatus auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseStatusUpdatableFieldsEquals(CaseStatus expected, CaseStatus actual) {
        assertThat(actual)
            .as("Verify CaseStatus relevant properties")
            .satisfies(a -> assertThat(a.getCaseStatusName()).as("check caseStatusName").isEqualTo(expected.getCaseStatusName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCaseStatusUpdatableRelationshipsEquals(CaseStatus expected, CaseStatus actual) {
        // empty method
    }
}
