package com.lawyer.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CourtAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourtAllPropertiesEquals(Court expected, Court actual) {
        assertCourtAutoGeneratedPropertiesEquals(expected, actual);
        assertCourtAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourtAllUpdatablePropertiesEquals(Court expected, Court actual) {
        assertCourtUpdatableFieldsEquals(expected, actual);
        assertCourtUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourtAutoGeneratedPropertiesEquals(Court expected, Court actual) {
        assertThat(actual)
            .as("Verify Court auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourtUpdatableFieldsEquals(Court expected, Court actual) {
        assertThat(actual)
            .as("Verify Court relevant properties")
            .satisfies(a -> assertThat(a.getCourtName()).as("check courtName").isEqualTo(expected.getCourtName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCourtUpdatableRelationshipsEquals(Court expected, Court actual) {
        // empty method
    }
}
